### PR TITLE
added charsets windows-125X

### PR DESCRIPTION
**Pull request by cseeger-epages**

### CODE REVIEW

**Comment by cseeger-epages** [comment]
@emersion yes actually :D i use your go-message lib in [mail2most](https://github.com/cseeger-epages/mail2most) and some of the users reported problems when getting different emails. With the character encoding at least 3 of them i have been able to reproduce so i choosed to add them all.

**Comment by cseeger-epages** [comment]
@emersion anything to do here ?

**Comment by cseeger-epages** [comment]
any chance to get this merged ?

**Comment by emersion** [comment]
I'd prefer not to do add all of these. Please only add those encountered in the wild.

The default set in go-message is supposed to parse most messages, but will never be able to parse all of them. Note, you can register additional go-message charsets in your app if needed.

**Comment by cseeger-epages** [comment]
@emersion ah i missed the `func RegisterEncoding(name string, enc encoding.Encoding)` function thats a very good point indeed. I added the missing charsets using this method so there is no need to merge this PR anymore if you dont want it. Thanks for your help.

**Pull request closed without merging**
