### PR TITLE
Tolerate (incorrect) folding whitespace used in base64 encoded body content.

### LINKED ISSUE #151: Does not correctly ignore 'bad' base64 whitespace characters RFC-2045
Honestly, I'm surprised to see this.  Got a really unusual error about being unable to decode a base64 transfer encoded part today. The part in question was an image that was wrapped at 998 chars long but _indented with a continuation white space_, which breaks the base64 decoder.

This is obviously a bug on the author of the mail part. HOWEVER I went and read the spec, RFC-2045 6.8 [()](https://datatracker.ietf.org/doc/html/rfc2045#section-6.8) and the following is stated:

> The encoded output stream must be represented in lines of no more
   than 76 characters each.  All line breaks or other characters not
   found in Table 1 must be ignored by decoding software.  In base64
   data, characters other than those in Table 1, line breaks, and other
   white space probably indicate a transmission error, about which a
   warning message or even a message rejection might be appropriate
   under some circumstances.
   
So, that's 2 counts that the part is breaking the spec on (line length and invalid characters) BUT I read this paragraph that we should be able to ignore this padding white space, and decode the part.

I believe this can be achieved by imitating what the base64 decoder does internally with it's `newlineFilteringReader`, we can wrap the raw reader in one that will do exactly the same, but include FWS (folding white space) characters in the list, so space and tab characters.

Would a PR for this be acceptable?

### PR DESCRIPTION
**Pull request by Spiral90210**
Fixes #151

### CODE REVIEW

**Comment by Spiral90210** [comment]
Any thoughts on accepting this PR? Fixes a problem we see with real world mail, yes it technically shouldn't be happening, but as with most things email there's always something writing mail that does so badly. Always.

**Comment by emersion** [comment]
Can we maybe replace `' '` and `'\t'` with `'\n'` which already gets ignored by encoding/base64? That way no need to deal with count/offset changes etc.

**Comment by Spiral90210** [comment]
It's actually based on the code from `base64.go`, just extended to account for these extra characters - I figured extending that would make more sense than wrapping/filtering twice.


Here's the original code from the standard library:

```go
type newlineFilteringReader struct {
	wrapped io.Reader
}

func (r *newlineFilteringReader) Read(p []byte) (int, error) {
	n, err := r.wrapped.Read(p)
	for n > 0 {
		offset := 0
		for i, b := range p[:n] {
			if b != '\r' && b != '\n' {
				if i != offset {
					p[offset] = b
				}
				offset++
			}
		}
		if offset > 0 {
			return offset, err
		}
		// Previous buffer entirely whitespace, read again
		n, err = r.wrapped.Read(p)
	}
	return n, err
}
```

**Comment by emersion** [comment]
> I figured extending that would make more sense than wrapping/filtering twice.

Hm but the wrapping is done internally by the standard library anyways right?

**Comment by emersion** [comment]
Thanks!

**Comment by Spiral90210** [comment]
> > I figured extending that would make more sense than wrapping/filtering twice.
> 
> Hm but the wrapping is done internally by the standard library anyways right?

Yup 🙄 clearly I was just satisfied with it working and then just went to live in fantasy land for a while!

**Pull request merged**
